project/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),


    #authentication
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/signup/', views.signup_view, name='signup'),
    path('accounts/logout/', views.logout_view, name='logout'),


    #profile
    path('profile/', views.profile_view, name="profile"),

    #upload profile pic
    path('profile-picture/upload/', views.profile_pic_upload, name="profile_pic_upload"),




    ########################################################################################
    #url paths for librarian user

    #add book
    path('books/', views.books_view, name='books_view'),

    #update book_data
    path('book/update/<str:book_id>', views.book_update, name='book_update'),

    #delete book_data
    path('book/delete/<str:book_id>', views.book_delete, name='book_delete'),

    #view book requests
    path('book/requests/', views.book_request_view, name='book_request_view'),


    #checkouts
    path('books/checkouts/', views.checkouts, name="checkouts"),


    ########################################################################################





    ########################################################################################

    #url paths for normal user

    #view books list for user
    path('user/books/', views.books_view_user, name='books_view_user'),

    #request a book
    path('request/book/<str:book_id>', views.add_book_request, name='add_book_request'),

    ########################################################################################

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime







class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    is_librarian = models.BooleanField(default=False)
    mobile_number = models.IntegerField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #if multiple roles
    #roles = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.user.username



class Book(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    c_class = models.CharField(max_length=100)
    stock = models.IntegerField()

    category_choices = [
        ('Information Technology', 'Information Technology'),
        ('Science', 'Science'),
        ('General', 'General'),
        ('Social Science', 'Social Science'),
        ('Arts', 'Arts'),
        ('Literature', 'Literature'),
        ('Physcology', 'Physcology'),
        ('Management', 'Management'),
        ('Economy', 'Economy'),
    ]

    category = models.CharField(max_length=100, choices=category_choices)
    description = models.TextField(blank=True, null=True)


    def __str__(self):
        return self.name + ' by ' + self.author
    

    @classmethod
    def get_categories(cls):
        return [category for category, _ in cls.category_choices]

    #custom method



class Book_ISBN(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='isbns')
    created_at = models.DateTimeField(auto_now_add=True)
    issued = models.BooleanField(default=False)


    def __str__(self):
        return self.book.name + ' | ISBN: ' + str(self.id)
    



class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name='checkouts')
    book_isbn = models.ForeignKey(Book_ISBN, on_delete=models.DO_NOTHING, null=True, related_name='checkouts')
    issued_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='checkouts_done', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField(blank=True, null=True)


    def set_expiry_date(self):
        # self.expiry_date = self.created_at + datetime.timedelta(days=14)
        return None


    def set_issued_by(self, user):
        self.issued_by = user


    def __str__(self):
        return self.book.name + ' - ' + self.user.username
    

    def save(self, *args, **kwargs):
        self.set_expiry_date()

        self.set_issued_by(kwargs.pop('librarian', None))

        super(Checkout, self).save(*args, **kwargs)



class BookRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='book_requests')
    book = models.ForeignKey(Book, on_delete=models.DO_NOTHING , related_name='requests')
    requested_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + ' requested ' + self.book.name

project/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from . helpers import is_valid_phone_number
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse

from . import models
from .models import Book

from . decorators import has_to_be_librarian



@login_required
@has_to_be_librarian
def checkouts(request):

    if request.method == "POST":

        form_data = request.POST
        user = User.objects.get(username=form_data['username'])
        book = Book.objects.get(id=form_data['book_id'])
        book_isbns = models.Book_ISBN.objects.filter(book=book).filter(issued=False)

        if book_isbns[0] is not None:
            new_checkout = models.Checkout(
                user = user,
                book_isbn = book_isbns[0],
            )
            new_checkout.save(librarian=request.user)


            book_isbns[0].issused = True
            book.stock = book.stock-1
            book_isbns[0].save()
            book.save()

            messages.success(request, 'Book checked out successfully')
            return redirect('main:checkouts', permanent=True)

        messages.error(request, 'Book out of stock')
        return redirect('main:checkouts', permanent=True)



    books = Book.objects.all()
    profiles = models.Profile.objects.filter(is_librarian=False)
    checkouts = models.Checkout.objects.all()
    context = {
        'books': books,
        'profiles': profiles,
        'checkouts':checkouts
    }

    return render(request, 'main/book_checkouts.html', context)


@login_required
@has_to_be_librarian
def book_request_view(request):
    requests = models.BookRequest.objects.all()

    context = {
        'requests': requests,
    }

    return render(request, 'main/book_requests.html', context)



@login_required
def add_book_request(request, book_id):

    try:

        try:
            book = Book.objects.get(id=book_id)
            book_request = models.BookRequest.objects.filter(book=book).filter(user=request.user)
            if book_request:
                messages.error(request, 'Book already requested')
                return redirect('main:books_view_user')

        except models.BookRequest.DoesNotExist:
            pass

        models.BookRequest.objects.create(
            user = request.user,
            book = book
        )

        messages.success(request, 'Book requested successfully')    

        return redirect("main:books_view_user")
    

    except Book.DoesNotExist:
        messages.error(request, 'Book not found')
        return redirect('main:books_view_user')



@login_required
def books_view_user(request):
    books = Book.objects.all()
    context = {
        'books':books,
    }
    return render(request, 'main/books.html', context)




@login_required
@has_to_be_librarian
def book_delete(request, book_id):
    print("accessed delete")
    try:
        book = Book.objects.get(id=book_id)
        book.delete()
        messages.success(request, 'Book deleted successfully')
        return redirect('main:books_view', permanent=True)
    except:
        messages.error(request, 'Book not found')
        return redirect('main:books_view', permanent=True)


@login_required
@has_to_be_librarian
def book_update(request, book_id):

    if request.method == "POST":
        try:
            book = Book.objects.get(id=book_id)
            book.name = request.POST['name']
            book.author = request.POST['author']
            book.c_class = request.POST['class']
            book.stock = request.POST['stock']
            book.category = request.POST['category']
            book.description = request.POST['description']
            book.save()
            messages.success(request, 'Book updated successfully')
            return redirect('main:books_view', permanent=True)
        except Book.DoesNotExist:
            messages.error(request, 'Book not found')
            return redirect('main:books_view', permanent=True)


    
    return HttpResponse("Wrong request",status=400)

@login_required
@has_to_be_librarian
def books_view(request):

    if request.method=="POST":
        form_data = request.POST
        name = form_data['name']
        author = form_data['author']
        class_ = form_data['class']
        stock = form_data['stock']
        category = form_data['category']
        description = form_data['description']

        book = Book()
        book.name = name
        book.author = author
        book.c_class = class_
        book.stock = stock
        book.category = category
        book.description = description
        book.save()

        for i in range(0, int(stock)):
            models.Book_ISBN.objects.create(
                book = book
            )


        messages.success(request, 'Book added successfully, auto added ISBNs')
        return redirect('main:books_view', permanent=True)


    #getting categories to show in form
    categories = Book.get_categories()
    books = Book.objects.all()
    context = {
        'categories': categories,
        'books': books
    }
    return render(request, 'main/books.html', context)


@require_http_methods(["POST"])
@login_required
def profile_pic_upload(request):
    print(request.method,"*****************************")
    if request.method == "POST":
        image = request.FILES.get('profile_img')

        if image:
            try:
                profile = models.Profile.objects.get(user=request.user)
            except models.Profile.DoesNotExist:
                profile = models.Profile.objects.create(user=request.user)

            if profile:
                profile.image = image
                profile.save()
                messages.success(request, 'Profile picture updated successfully')
                return redirect('main:profile', permanent=True)
            else:
                messages.error(request, 'Error updating profile picture, profile not found')
                return redirect('main:profile', permanent=True)    
        
        else:
            messages.error(request, 'Error updating profile picture')
            return redirect('main:profile', permanent=True)
            

    


@login_required
def profile_view(request):
    if request.method=="POST":
        # print(request.POST)
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        mobile_number = request.POST['mobile_number']




        if not is_valid_phone_number(mobile_number):
            messages.error(request, 'Please enter a valid phone number')
            return redirect('main:profile', permanent=True)

        if (request.user.first_name == "" or request.user.last_name == ""):
            if len(first_name) < 2  or len(last_name) < 2:
                messages.error(request, 'First and last names must be at least 2 characters long')
                return redirect('main:profile', permanent=True)



        user = request.user
        user.first_name = first_name if first_name!="" else user.first_name
        user.last_name = last_name if last_name!="" else user.last_name
        user.save()

        try:
            profile = models.Profile.objects.get(user=request.user)
            profile.mobile_number = mobile_number
            profile.save()
        except models.Profile.DoesNotExist:
            models.Profile.objects.create(
                user=user,
                mobile_number=mobile_number
            )

        messages.success(request, 'Profile updated successfully')
        return redirect('main:profile', permanent=True)


    return render(request, 'main/profile.html')


@login_required
def dashboard(request):
    return render(request, 'main/dashboard.html')



def login_view(request):

    if request.method == "POST":
        data = request.POST

        username = data['username']
        password = data['password']

        # user = User.objects.filter(username=username).first()
        user = authenticate(request, username=username, password=password)

        if user:
            # if user.check_password(password):  #you can use this too
            login(request, user)
            return redirect('main:dashboard')
            
        else:
            messages.error(request, 'Invalid Credentials')

            return redirect("main:login")


    return render(request, 'main/login.html')







def signup_view(request):

    if request.method == "POST":
        data = request.POST

        username = data['username']

        #check if username already exists
        try:
            User.objects.get(username=username)

            #generate auto username using random module and use your own creative logic

            messages.error(request, f'User with {username} already exists, try another username')
        except User.DoesNotExist:
             #username validation    
            if len(username) < 6:
                messages.error(request, 'Username must be at least 6 characters long')

                context = {
                    'old_data': data,
                }
                return render(request, 'main/signup.html', context)
            

            #password length validation
            if len(data['password']) < 6:
                messages.error(request, 'Password must be at least 6 characters long')

                context = {
                    'old_data': data,
                }
                return render(request, 'main/signup.html', context)
            
            else:
                #password match validation
                if data['password'] != data['confirm_password']:
                    messages.error(request, 'Password and Confirm Password do not match')

                    context = {
                        'old_data': data,
                    }

project/main/templates/main/books.html
{% extends 'main/base.html' %}

{% block title %}Add Book

{% endblock title %}

{% block messages %}

<div class="messages">
    
  {% if messages %}
  {% for message in messages %}
    <div class="message-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
  {% endif %}
  </div>
  

{% endblock messages %}




{% block page_name %} Books {% endblock page_name %}

{% block page_top_bar_end_section %}

{% if request.user.profile.is_librarian %}
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addBookModal">
   Add
  </button>


    <!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="addBookModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addBookModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addBookModalLabel">Add New Book</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" required>
              </div>
            <div class="mb-3">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" name="author" aria-describedby="authorHelp" required>
              </div>
            <div class="mb-3">
                <label for="class" class="form-label">Class</label>
                <input type="text" class="form-control" id="class" name="class" aria-describedby="classHelp" required>
              </div>
            <div class="mb-3">
                <label for="stock" class="form-label">Stock</label>
                <input type="number" class="form-control" id="stock" name="stock" aria-describedby="stockHelp" required>
              </div>
            <div class="mb-3">
                <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="category">
                    {% for category in categories %}

                    {% if forloop.first %}
                    <option value="{{ category }}" selected>{{category}}</option>

                    {% else %}
                    <option value="{{ category }}">{{category}}</option>
                    {% endif %}
                    
                    {% endfor %}
                  </select>
              </div>
              <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3"></textarea>
              </div>

              <button type="submit" class="btn btn-primary">Add </button>


          </form>
        </div>
        
      </div>
    </div>
  </div>

  {% endif %}

  {% endblock page_top_bar_end_section %}




{% block content %}

<table class="table table-stripped">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Book ID</th>
      <th scope="col">Name</th>
      <th scope="col">Author</th>
      <th scope="col">Stock</th>
      <th scope="col">Category</th>
      <th scope="col">Description</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for book in books %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{book.id}}</td>
      <td>{{book.name}}</td>
      <td>{{book.author}}</td>
      <td>{{book.stock}}</td>
      <td>{{book.category}}</td>
      <td>{{book.description}}</td>
      <td>
        <div class="d-flex justify-content-center gap-2 align-items-center">
          {% if request.user.profile.is_librarian %}
          <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#book-{{book.id}}">
            Update
           </button>
         
         
             <!-- Button trigger modal -->
         
           
           <!-- Modal -->
           <div class="modal fade" id="book-{{book.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="book-{{book.id}}Label" aria-hidden="true">
             <div class="modal-dialog">
               <div class="modal-content">
                 <div class="modal-header">
                   <h5 class="modal-title" id="book-{{book.id}}Label">Update Book</h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                 </div>
                 <div class="modal-body">
                   <form action="{% url 'main:book_update' book.id %}" method="post">
                     {% csrf_token %}
         
                     <div class="mb-3">
                         <label for="name" class="form-label">Name</label>
                         <input type="text" class="form-control" id="name" value="{{book.name}}" name="name" aria-describedby="nameHelp" required>
                       </div>
                     <div class="mb-3">
                         <label for="author" class="form-label">Author</label>
                         <input type="text" class="form-control" id="author" value="{{book.author}}" name="author" aria-describedby="authorHelp" required>
                       </div>
                     <div class="mb-3">
                         <label for="class" class="form-label">Class</label>
                         <input type="text" class="form-control" id="class" name="class" value="{{book.c_class}}" aria-describedby="classHelp" required>
                       </div>
                     <div class="mb-3">
                         <label for="stock" class="form-label">Stock</label>
                         <input type="number" class="form-control" id="stock" name="stock" value="{{book.stock}}" aria-describedby="stockHelp" required>
                       </div>
                     <div class="mb-3">
                         <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="category">
                             {% for category in categories %}
         
                             <option value="{{ category }}" 
                             {% if book.category == category %}
                             selected
                             {% endif %}
                             
                             >{{category}}</option>
                             
                             {% endfor %}
                           </select>
                       </div>
                       <div class="mb-3">
                         <label for="description" class="form-label">Description</label>
                         <textarea class="form-control" id="description" name="description" rows="3">{{book.description}}</textarea>
                       </div>
         
                       <button type="submit" class="btn btn-primary">Update </button>
         
         
                   </form>
                 </div>
                 
               </div>
             </div>
           </div>

          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#book-{{book.id}}-delete">
            Delete
           </button>
         
         
             <!-- Button trigger modal -->
         
           
           <!-- Modal -->
           <div class="modal fade" id="book-{{book.id}}-delete" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="book-{{book.id}}-deleteLabel" aria-hidden="true">
             <div class="modal-dialog">
               <div class="modal-content">
                 <div class="modal-header">
                   <h5 class="modal-title" id="book-{{book.id}}-deleteLabel">Are you sure, you want to delete this book record? </h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                 </div>
                 <div class="modal-body">
                    <a href="{% url 'main:book_delete' book.id %}" class="btn btn-danger">Delete</a>
                 </div>
                 
               </div>
             </div>
           </div>



           {% else %}
           {% comment %} {{ book.requests.all }} {% endcomment %}

           {% if book.requests.all %}
           {% for request in book.requests.all  %}
            {% if request.book.id != book.id %}
              <a href="{% url 'main:add_book_request' book.id %}" class="btn btn-primary">Request </a>
              
              {% endif %}
              
              
              {% endfor %}
              {% else %}
              <a href="{% url 'main:add_book_request' book.id %}" class="btn btn-primary">Request </a>
           {% endif %}
           
          
           
           
           




          {% endif %}
        </div>

      </td>
    </tr>
    
    {% endfor %}
    
  </tbody>
</table>

{% endblock content %}

project/main/templates/main/dashboard.html
{% extends 'main/base.html' %} {% load static %} 
{% block page_top_bar %}

{% endblock page_top_bar %} 
{% block title %} Dashboard | LMS {% endblock title %}

project/main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}
Login | LMS

{% endblock title %}



{% block messages %}
{% if messages %}
  {% for message in messages %}
    <div class="message-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

{% endblock messages %}


{% block sidebar %}{% endblock sidebar %}

{% block page_top_bar %}{% endblock page_top_bar %}


{% block content %}
<div class="container">
    <form class="login-form" method="post">
        {% csrf_token %}
        <h4 class="my-4">Login Form</h4>
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input type="text" class="form-control" id="username" name="username" aria-describedby="usernameHelp" required>
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <div class="password-input d-flex align-items-center" >
            <input type="password" class="form-control" name="password" id="password" required>
            <i id="eyeBtn" class="fa fa-eye"></i>
            <i id="eyeSlashBtn" class="fa fa-eye-slash"></i>

          </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'main:signup' %}">Not registered yet?</a>
    </form>

</div>

{% endblock content %}


{% block internaljs %}

    <script>
        const eyeBtnEl = document.getElementById("eyeBtn")
        const eyeSlashBtnEl = document.getElementById("eyeSlashBtn")
        const passwordInputEl = document.getElementById("password")


        eyeBtnEl.addEventListener('click', ()=>{

            if (passwordInputEl.type === "password") {
                passwordInputEl.type = "text";
                eyeBtnEl.style.display = "none"
                eyeSlashBtnEl.style.display = "block"
                
            }      
        })


              eyeSlashBtnEl.addEventListener('click',()=>{
                if (passwordInputEl.type === "text") {
                    passwordInputEl.type = "password";
                    eyeSlashBtnEl.style.display = "none"
                    eyeBtnEl.style.display = "block"
                    
                }   
              })

    </script>
{% endblock internaljs %}

project/main/templates/main/profile.html
{% extends 'main/base.html' %}
{% comment %} {% load static %} {% endcomment %}
{% block title %}
    
{{request.user.username}} | Profile

{% endblock title %}

{% block messages %}

<div class="messages">
    
{% if messages %}
{% for message in messages %}
  <div class="message-{{ message.tags }}">
    {{ message }}
  </div>
{% endfor %}
{% endif %}
</div>

{% endblock messages %}



{% block page_name %}

    {% if request.user.first_name %}
        {{ request.user.first_name }} | Profile
    {% else %}
    {{request.user.username}} | Profile

    {% endif %}

{% endblock page_name %}

{% block content %}

    <div class="profile-info">
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">

                        {% if request.user.profile.image %}
                        <img class="rounded-circle mt-5" width="150px" src="{{ request.user.profile.image.url }}" alt="userimage">


                        {% else %}
                        <img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg">

                        <form action="{% url 'main:profile_pic_upload' %}" method="post" enctype="multipart/form-data" >
                            {% csrf_token %}
                            <input type="file" name="profile_img" id="profile_img">

                            <button type="submit" class="btn btn-primary">Upload</button>

                        </form>


                        {% endif %}
                        
                        
                        
                        <span class="font-weight-bold">


                        {% if request.user.first_name %}
                        {{ request.user.first_name }} | Profile {% if request.user.profile.is_librarian %}
                        |  Librarian
                            {% endif %}
                    {% else %}
                    {{request.user.username}} | Profile  {% if request.user.profile.is_librarian %}
                           |  Librarian
                    
                    {% endif %}
                
                    {% endif %}
                    </span><span class="text-black-50">
                        {% if request.user.email %}
                        {{ request.user.email }}
                    {% else %}
                      please add email
                
                    {% endif %}

                    </span><span> </span></div>
                </div>
                <div class="col-md-5 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Profile Info</h4>
                        </div>
                        <form action="" method="post" >
                            {% csrf_token %}
                        <div class="row mt-2">

                            <div class="col-md-6"><label class="labels">Name</label><input minlength="2" name="first_name" type="text" class="form-control" placeholder="{% if request.user.first_name %}{{ request.user.first_name }}{% else %}Add first name
                                {% endif %}"  value="" ></div>
                            <div class="col-md-6"><label class="labels">Surname</label><input minlength="2" name="last_name" type="text" class="form-control" value="" placeholder="{% if request.user.last_name %}{{ request.user.last_name }}{% else %}Add last name
                                {% endif %}" ></div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12"><label class="labels">Mobile Number</label><input name="mobile_number" type="text" class="form-control" placeholder="{% if request.user.profile.mobile_number %}{{ request.user.profile.mobile_number }}{% else %}enter phone number
                                {% endif %}" value=""></div>
                            
                        </div>

                        <button class="btn btn-primary mt-3">
                            Update
                        </button>
                    </form>
                        
                    </div>
                </div>
                
            </div>
        </div>
        </div>
        </div>
           
         
    </div>

{% endblock content %}